#!/usr/bin/bash

# Base dots dir (where this file lives) and the XDG_CONFIG_DIR
CONF_DIR="${XDG_CONFIG_HOME:-${HOME}/.config}"
DOTS=$(dirname $(readlink -e ${0}))

LOCAL_BIN="${HOME}/.local/bin"

printf "%s\n" "---------------- LINKING UP ---------------------------"
printf "Linking to configuration directory: %s\n" "${CONF_DIR}"
printf "Linking to local binaries directory: %s\n" "${LOCAL_BIN}"
printf "%s\n" "-------------------------------------------------------"

# link_default DOTS_PATH CONF_DIR_PATH NICKNAME
link_default() {
	if test -d "${CONF_DIR}/${2}"; then
		printf "${3} configuration present, skipping\n"
	elif test -e "${CONF_DIR}/${2}" || test -h "${CONF_DIR}/${2}"; then
		printf "${3} has some non-directory present (possibly proper symlink), skipping\n"
	else
		ln -s "${DOTS}/${1}" "${CONF_DIR}/${2}"
		printf "${3} configuration linked\n"
	fi
}

# link_file_direct FROM_PATH TO_PATH NICKNAME
link_file_direct() {
	if test -f "${2}" && test ! -h "${2}"; then
		printf "${3} already present, moving to backup first\n"
		mv "${2}" "${2}.bak"
	fi

	if test -h "${2}"; then
		printf "${3} already linked, skipping\n"
	else
		ln -s "${1}" "${2}"
		printf "${3} linked\n"
	fi
}

# link_folder_direct FROM_PATH TO_PATH NICKNAME
link_folder_direct() {
	if test -d "${2}" && test ! -h "${2}"; then
		printf "${3} already present, moving to backup first\n"
		mv "${2}" "${2}.bak"
	fi

	if test -h "${2}"; then
		printf "${3} already linked, skipping\n"
	else
		ln -s "${1}" "${2}"
		printf "${3} linked\n"
	fi
}

link_default nvim nvim Neovim
link_default zathura zathura Zathura
link_default foot foot Foot
link_default river river River
link_default waybar waybar Waybar
link_default wofi wofi Wofi
link_default gtk-3.0 gtk-3.0 "GTK 3"

link_file_direct "${DOTS}/homedir/.bashrc" "${HOME}/.bashrc" "Bash config"
link_file_direct "${DOTS}/homedir/.bash_profile" "${HOME}/.bash_profile" "Bash profile"
link_file_direct "${DOTS}/homedir/.gitconfig" "${HOME}/.gitconfig" "Git config"


printf "%s\n" "------------ EWW CONFIGURATION ---------------"

EWW_BIN="${DOTS}/eww/local-clone/target/release/eww"
if ! command -v eww 2&>1 >/dev/null; then
    printf "%s\n" "------ EWW BINARY NOT FOUND, BUILDING -------------"
    cd "${DOTS}/eww/local-clone/"
    cargo build --release --no-default-features --features=wayland
    cd -
    if ! [[ $? == 0 ]]; then
        printf "%s\n" "------------ EWW BINARY BUILT ----------"
    else
        printf "%s\n" "---- FAILED TO BUILD EWW BINARY, EXITING -------"
        exit 0
    fi
    chmod +x "${EWW_BIN}"
    link_file_direct "${EWW_BIN}" "${LOCAL_BIN}/eww" "EWW Binary"
fi

link_folder_direct "${DOTS}/eww/config" "${CONF_DIR}/eww" "EWW Config"

if ! [[ -f "${CONF_DIR}/eww/scripts/battery-tooltip" ]]; then
    cd "${CONF_DIR}/eww/scripts/"
    rustc battery-tooltip.rs
    EC=$?
    cd -
    if ! [[ $EC == 0 ]]; then
        printf "%s\n" "Failed to compile battery-tooltip.rs"
    fi
fi
