#!/usr/bin/bash

# Base dots dir (where this file lives) and the XDG_CONFIG_DIR
CONF_DIR="${XDG_CONFIG_HOME:-${HOME}/.config}"
DOTS=$(dirname $(readlink -e ${0}))

printf "%s\n" "---------------- LINKING UP ---------------------------"
printf "Linking to configuration directory: %s\n" "${CONF_DIR}"
printf "%s\n" "-------------------------------------------------------"

# link_default DOTS_PATH CONF_DIR_PATH NICKNAME
link_default() {
	if test -d "${CONF_DIR}/${2}"; then
		printf "${3} configuration present, skipping\n"
	elif test -e "${CONF_DIR}/${2}" || test -h "${CONF_DIR}/${2}"; then
		printf "${3} has some non-directory present (possibly proper symlink), skipping\n"
	else
		ln -s "${DOTS}/${1}" "${CONF_DIR}/${2}"
		printf "${3} configuration linked\n"
	fi
}

# link_file_direct FROM_PATH TO_PATH NICKNAME
link_file_direct() {
	if test -f "${2}" && test ! -h "${2}"; then
		printf "${3} already present in home directory, moving to backup first\n"
		mv "${2}" "${2}.bak"
	fi

	if test -h "${2}"; then
		printf "${3} already linked, skipping\n"
	else
		ln -s "${1}" "${2}"
		printf "${3} linked"
	fi
}

link_default nvim nvim Neovim
link_default foot foot Foot
link_default river river River
link_default waybar waybar Waybar

link_file_direct "${DOTS}/homedir/.bashrc" "${HOME}/.bashrc" "Bash config"
link_file_direct "${DOTS}/homedir/.gitconfig" "${HOME}/.gitconfig" "Git config"
