#!/usr/bin/env bash

TOGGLE_TARGET="${1}"

if [ -z "$TOGGLE_TARGET" ]; then
    exit 1
fi

RES=$(eww active-windows | rg "$TOGGLE_TARGET")

if [ -z "${RES}" ]; then
    eww open "$TOGGLE_TARGET" >/dev/null
else
    eww close "${TOGGLE_TARGET}" >/dev/null
fi
