#!/usr/bin/env bash

PLAYER="$(eww get player)"


case $PLAYER in
    mpd)
        mpc -f "%title% - %artist%" current
        eww update "player-status=$(mpc status '%state%')"
        while true; do
            mpc idle player >/dev/null
            mpc -f "%title% - %artist%" current
            eww update "player-status=$(mpc status '%state%')"
        done
        ;;
	spotify)
		case "$1" in
			--time)
				ttime=$(playerctl -p spotify -f '{{mpris:length}}' metadata)
				ttime_sec=$((ttime/1000000))
				ctime=$(playerctl -p spotify position)
				echo "{\"ttime\":\"$ttime_sec\", \"ctime\":\"$ctime\"}"
				exit 0;
				;;
		esac
		playerctl -p spotify -F -f '{"status":"{{lc(status)}}","album":"{{xesam:album}}","title":"{{xesam:title}}","artist":"{{xesam:artist}}","artUrl":"{{mpris:artUrl}}"}' metadata
        ;;
    *)
        notify-send "EWW Now Playing" "No working $PLAYER Now Playing implementation"
        ;;
esac
