#!/usr/bin/env bash

PLAYER="$(eww get player)"

case $PLAYER in
    mpd)
        mpc -f "%title% - %artist%" current
        eww update "player-status=$(mpc status '%state%')"
        while true; do
            mpc idle player >/dev/null
            mpc -f "%title% - %artist%" current
            eww update "player-status=$(mpc status '%state%')"
        done
        ;;
	spotify)
		playerctl -p spotify -F -f '{"status":"{{lc(status)}}","album":"{{album}}","title":"{{title}}","artist":"{{artist}}","artUrl":"{{artUrl}}"}' metadata
        ;;
    *)
        notify-send "EWW Now Playing" "No working $PLAYER Now Playing implementation"
        ;;
esac
